name: Continuous Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    tags: [v*]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings


  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


  build:
    name: Test Rust ${{ matrix.toolchain }} on ${{ matrix.os }}
    needs: [clippy, rustfmt]
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        toolchain: [nightly]
        os: [ubuntu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Remove .lock file
        run: rm Cargo.lock

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

